### ISSUE TITLE
Heroku addons

### ISSUE THREAD

**Issue by rurounijones** [tokyorails/tokyorails#15]
I am looking at the various heroku addons which may be useful for this site. I think the following would be worth looking at since we are shooting for a "Best Practices" app:

Loggly (Free): 

I think all "Best Practices" apps should have some sort of centralised logging system. In our case it would also help to put our logs onto a 3rd party service that everyone can access so we can see production logs without heroku access

NewRelic (Free):

Does anyone NOT use newrelic in their apps? Again it will let everyone involved see the sort of information NewRelic can offer if they haven't used it before.

I am not sure how much we can spend on this but having the Airbrake addon ($2) would also be good so that we can track exceptions. For example if the scheduled member import script I wrote fails for some reason.

Whaddayathink?

**Comment by tapster** [comment]
nice idea. funnily enough, I blogged something similar a while back but now I see it's woefully out of date... http://tech.cookpad.com/2011/06/6-must-have-heroku-addons-before-you-get-started.html

loggly looks interested. free for up to 200MB/day which should be fine. I think we can use the basic airbrakeapp for free too if we dont install as an addon, just manually add

new relic like you said, definitely everyone should use! 

I'll add stories for each of these a well as setting up cron, so I dont forget

**Comment by rurounijones** [comment]
I can see New Relic and Airbrake have been added to the code. Has loggly been added heroku side? If so I shall close this ticket

**Comment by tapster** [comment]
I originally added it via heroku, but noticed loggly had a free account that offers 4x the limits, so I just swapped it over to use the loggly direct version. need to figure out how to share the credentials to log in. I guess whoever wants them is ok for external services

**Comment by rurounijones** [comment]
Okey dokey, I will close this issue since it is extraneous now.
