### ISSUE TITLE
Member Login and Join to Project is broken

### ISSUE THREAD

**Issue by CaDs** [tokyorails/tokyorails#47]
Is raising a lot of  Invalid Authorization request errors coming from Meetup

I will try to fix it if no one else is working on it

**Comment by tapster** [comment]
Oh dear. is it still happening for you? could be that meetup API was down maybe?

**Comment by CaDs** [comment]
Yes, is still happening.
Looks like is some kind of problem with the meetup API. Once I have a session open with meetup, if I go to the tokyorails page and try to log in, the same error keeps happening.

**Comment by tapster** [comment]
thanks for checking again. for some reason I cant reproduce with my account... if you get chance can you list the steps and any idea you have why it's happening? must be something about the state of your login that I haven't replicated right on my end... thanks again!

**Comment by tapster** [comment]
I did find an issue with authentication that should now be resolved! If you have chance, can you try and authenticate at tokyorails.org again? cheers!

**Comment by CaDs** [comment]
works like a charm! Thanks :+1:
